chessboard/urls.py
#from chessboard.chessboardApp.views import rules
from django.contrib import admin
from django.urls import include, path
from chessboardApp import views as app_views

urlpatterns = [
    path('chess/', include('chessboardApp.urls')),
    path('admin/', admin.site.urls),
]

chessboardApp/urls.py
from django.urls import path

from . import views
app_name = "chess"
urlpatterns = [
    path('', views.home, name = "home"),
    path('reset', views.reset, name = "reset"),
    path('rules', views.rules),
    path('history', views.history),
    path('about', views.about),
]

chessboardApp/models.py
from django.db import models

# Create your models here.


class Board(models.Model):
    board_name = models.CharField(max_length=30)
    def __str__(self):
        return self.board_name

class Space(models.Model):
    board = models.ForeignKey(Board, related_name="space_list", on_delete=models.CASCADE)
    space_col = models.CharField(max_length=1)
    space_row = models.IntegerField()
    space_piece = models.CharField(max_length=6)
    def __str__(self):
        row = str(self.space_row)
        col = str(self.space_col)
        conc = col + row
        return conc

chessboardApp/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from .models import Space, Board
from django.template import loader
from django.http import Http404

# Create your views here.
from django.http import HttpResponse
pieces = {
    "wPawn" : "&#9817",
    "wKnight" : "&#9816",
    "wBishop" : "&#9815",
    "wRook" : "&#9814",
    "wQueen" : "&#9813",
    "wKing" : "&#9812",
    "bPawn" : "&#9823",
    "bKnight" : "&#9822",
    "bBishop" : "&#9821",
    "bRook" : "&#9820",
    "bQueen" : "&#9819",
    "bKing" : "&#9818"
}

def home(request):
    if request.method == 'GET':
        try: #get saved board
            board = Board.objects.get(board_name = "putUserNameHere")
        except: #or create new one
            board = Board(board_name="putUserNameHere")
            board.save()
            board.space_list.create(space_row="8", space_col="a", space_piece=pieces['bRook'])
            board.space_list.create(space_row="8", space_col="b", space_piece=pieces['bKnight'])
            board.space_list.create(space_row="8", space_col="c", space_piece=pieces['bBishop'])
            board.space_list.create(space_row="8", space_col="d", space_piece=pieces['bKing'])
            board.space_list.create(space_row="8", space_col="e", space_piece=pieces['bQueen'])
            board.space_list.create(space_row="8", space_col="f", space_piece=pieces['bBishop'])
            board.space_list.create(space_row="8", space_col="g", space_piece=pieces['bKnight'])
            board.space_list.create(space_row="8", space_col="h", space_piece=pieces['bRook'])

            board.space_list.create(space_row="7", space_col="a", space_piece=pieces['bPawn'])
            board.space_list.create(space_row="7", space_col="b", space_piece=pieces['bPawn'])
            board.space_list.create(space_row="7", space_col="c", space_piece=pieces['bPawn'])
            board.space_list.create(space_row="7", space_col="d", space_piece=pieces['bPawn'])
            board.space_list.create(space_row="7", space_col="e", space_piece=pieces['bPawn'])
            board.space_list.create(space_row="7", space_col="f", space_piece=pieces['bPawn'])
            board.space_list.create(space_row="7", space_col="g", space_piece=pieces['bPawn'])
            board.space_list.create(space_row="7", space_col="h", space_piece=pieces['bPawn'])

            board.space_list.create(space_row="1", space_col="a", space_piece=pieces['wRook'])
            board.space_list.create(space_row="1", space_col="b", space_piece=pieces['wKnight'])
            board.space_list.create(space_row="1", space_col="c", space_piece=pieces['wBishop'])
            board.space_list.create(space_row="1", space_col="d", space_piece=pieces['wKing'])
            board.space_list.create(space_row="1", space_col="e", space_piece=pieces['wQueen'])
            board.space_list.create(space_row="1", space_col="f", space_piece=pieces['wBishop'])
            board.space_list.create(space_row="1", space_col="g", space_piece=pieces['wKnight'])
            board.space_list.create(space_row="1", space_col="h", space_piece=pieces['wRook'])

            board.space_list.create(space_row="2", space_col="a", space_piece=pieces['wPawn'])
            board.space_list.create(space_row="2", space_col="b", space_piece=pieces['wPawn'])
            board.space_list.create(space_row="2", space_col="c", space_piece=pieces['wPawn'])
            board.space_list.create(space_row="2", space_col="d", space_piece=pieces['wPawn'])
            board.space_list.create(space_row="2", space_col="e", space_piece=pieces['wPawn'])
            board.space_list.create(space_row="2", space_col="f", space_piece=pieces['wPawn'])
            board.space_list.create(space_row="2", space_col="g", space_piece=pieces['wPawn'])
            board.space_list.create(space_row="2", space_col="h", space_piece=pieces['wPawn'])

            board.space_list.create(space_row="3", space_col="a", space_piece="")
            board.space_list.create(space_row="3", space_col="b", space_piece="")
            board.space_list.create(space_row="3", space_col="c", space_piece="")
            board.space_list.create(space_row="3", space_col="d", space_piece="")
            board.space_list.create(space_row="3", space_col="e", space_piece="")
            board.space_list.create(space_row="3", space_col="f", space_piece="")
            board.space_list.create(space_row="3", space_col="g", space_piece="")
            board.space_list.create(space_row="3", space_col="h", space_piece="")
        
            board.space_list.create(space_row="4", space_col="a", space_piece="")
            board.space_list.create(space_row="4", space_col="b", space_piece="")
            board.space_list.create(space_row="4", space_col="c", space_piece="")
            board.space_list.create(space_row="4", space_col="d", space_piece="")
            board.space_list.create(space_row="4", space_col="e", space_piece="")
            board.space_list.create(space_row="4", space_col="f", space_piece="")
            board.space_list.create(space_row="4", space_col="g", space_piece="")
            board.space_list.create(space_row="4", space_col="h", space_piece="")

            board.space_list.create(space_row="5", space_col="a", space_piece="")
            board.space_list.create(space_row="5", space_col="b", space_piece="")
            board.space_list.create(space_row="5", space_col="c", space_piece="")
            board.space_list.create(space_row="5", space_col="d", space_piece="")
            board.space_list.create(space_row="5", space_col="e", space_piece="")
            board.space_list.create(space_row="5", space_col="f", space_piece="")
            board.space_list.create(space_row="5", space_col="g", space_piece="")
            board.space_list.create(space_row="5", space_col="h", space_piece="")

            board.space_list.create(space_row="6", space_col="a", space_piece="")
            board.space_list.create(space_row="6", space_col="b", space_piece="")
            board.space_list.create(space_row="6", space_col="c", space_piece="")
            board.space_list.create(space_row="6", space_col="d", space_piece="")
            board.space_list.create(space_row="6", space_col="e", space_piece="")
            board.space_list.create(space_row="6", space_col="f", space_piece="")
            board.space_list.create(space_row="6", space_col="g", space_piece="")
            board.space_list.create(space_row="6", space_col="h", space_piece="")
            board.save()
        context = {
            'board' : board,
        }  
        return render(request, 'chessboardApp/home.html', context)
    if request.method == 'POST':
        board = Board.objects.get(board_name = "putUserNameHere")
        from_field = request.POST.get('fromTextBox')
        to_field = request.POST.get('toTextBox')
        if to_field=="" or from_field=="":
            context = {
            'board' : board,
            }  
            return render(request, 'chessboardApp/home.html', context)
        if to_field=="RESET" or from_field=="RESET":
            #context = {
            #'board' : board,
            #}
            return render(request, 'chessboardApp/home.html', context)
        fromSpace = board.space_list.filter(space_col=from_field[0]).filter(space_row=from_field[1])
        fromSpace = fromSpace[0]
        toSpace = board.space_list.filter(space_col=to_field[0]).filter(space_row=to_field[1])[0]
        toSpace.space_piece = fromSpace.space_piece
        fromSpace.space_piece = ""
        toSpace.save()
        fromSpace.save()
        board.save()
        
        context = {
            'board' : board,
        }  
        return render(request, 'chessboardApp/home.html', context)
def rules(request):
    return render(request, 'chessboardApp/rules.html')

def history(request):
    return render(request, 'chessboardApp/history.html')

def about(request):
    return render(request, 'chessboardApp/about.html')
def reset(request):
    try: #get saved board
        board = Board.objects.get(board_name = "putUserNameHere")
        board.delete()
    except:
        x=1
    board = Board(board_name="putUserNameHere")
    board.save()
    board.space_list.create(space_row="8", space_col="a", space_piece=pieces['bRook'])
    board.space_list.create(space_row="8", space_col="b", space_piece=pieces['bKnight'])
    board.space_list.create(space_row="8", space_col="c", space_piece=pieces['bBishop'])
    board.space_list.create(space_row="8", space_col="d", space_piece=pieces['bKing'])
    board.space_list.create(space_row="8", space_col="e", space_piece=pieces['bQueen'])
    board.space_list.create(space_row="8", space_col="f", space_piece=pieces['bBishop'])
    board.space_list.create(space_row="8", space_col="g", space_piece=pieces['bKnight'])
    board.space_list.create(space_row="8", space_col="h", space_piece=pieces['bRook'])

    board.space_list.create(space_row="7", space_col="a", space_piece=pieces['bPawn'])
    board.space_list.create(space_row="7", space_col="b", space_piece=pieces['bPawn'])
    board.space_list.create(space_row="7", space_col="c", space_piece=pieces['bPawn'])
    board.space_list.create(space_row="7", space_col="d", space_piece=pieces['bPawn'])
    board.space_list.create(space_row="7", space_col="e", space_piece=pieces['bPawn'])
    board.space_list.create(space_row="7", space_col="f", space_piece=pieces['bPawn'])
    board.space_list.create(space_row="7", space_col="g", space_piece=pieces['bPawn'])
    board.space_list.create(space_row="7", space_col="h", space_piece=pieces['bPawn'])

    board.space_list.create(space_row="1", space_col="a", space_piece=pieces['wRook'])
    board.space_list.create(space_row="1", space_col="b", space_piece=pieces['wKnight'])
    board.space_list.create(space_row="1", space_col="c", space_piece=pieces['wBishop'])
    board.space_list.create(space_row="1", space_col="d", space_piece=pieces['wKing'])

chessboardApp/templates/bootstrap.html
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

chessboardApp/templates/chessIndex.html
<h1>CINS 465: Assignment 5 by Kurt Voigtritter</h1>
<div id="boardContainer">
    <table id="board">
        <!--Eight-->
        <tr id="eight">
            <th class="leftNumb">8</th>
            {% for spaces in board.space_list.all %}
            {% if spaces.space_row == 8 %}
            {% if spaces.space_col == "a" %}
            <td id="a8">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "b" %}
            <td id="b8">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "c" %}
            <td id="c8">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "d" %}
            <td id="d8">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "e" %}
            <td id="e8">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "f" %}
            <td id="f8">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "g" %}
            <td id="g8">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "h" %}
            <td id="h8">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% endif %}
            {% endfor %}
        </tr>
        <!--seven-->
        <tr id="seven">
            <th class="leftNumb">7</th>
            {% for spaces in board.space_list.all %}
            {% if spaces.space_row == 7 %}
            {% if spaces.space_col == "a" %}
            <td id="a7">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "b" %}
            <td id="b7">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "c" %}
            <td id="c7">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "d" %}
            <td id="d7">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "e" %}
            <td id="e7">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "f" %}
            <td id="f7">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "g" %}
            <td id="g7">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "h" %}
            <td id="h7">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% endif %}
            {% endfor %}
        </tr>
        <!--six-->
        <tr id="six">
            <th class="leftNumb">6</th>
            {% for spaces in board.space_list.all %}
            {% if spaces.space_row == 6 %}
            {% if spaces.space_col == "a" %}
            <td id="a6">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "b" %}
            <td id="b6">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "c" %}
            <td id="c6">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "d" %}
            <td id="d6">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "e" %}
            <td id="e6">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "f" %}
            <td id="f6">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "g" %}
            <td id="g6">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "h" %}
            <td id="h6">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% endif %}
            {% endfor %}
        </tr>
        <!--five-->
        <tr id="five">
            <th class="leftNumb">5</th>
            {% for spaces in board.space_list.all %}
            {% if spaces.space_row == 5 %}
            {% if spaces.space_col == "a" %}
            <td id="a5">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "b" %}
            <td id="b5">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "c" %}
            <td id="c5">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "d" %}
            <td id="d5">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "e" %}
            <td id="e5">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "f" %}
            <td id="f5">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "g" %}
            <td id="g5">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "h" %}
            <td id="h5">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% endif %}
            {% endfor %}

        </tr>
        <!--4-->
        <tr id="four">
            <th class="leftNumb">4</th>
            {% for spaces in board.space_list.all %}
            {% if spaces.space_row == 4 %}
            {% if spaces.space_col == "a" %}
            <td id="a4">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "b" %}
            <td id="b4">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "c" %}
            <td id="c4">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "d" %}
            <td id="d4">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "e" %}
            <td id="e4">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "f" %}
            <td id="f4">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "g" %}
            <td id="g4">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "h" %}
            <td id="h4">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% endif %}
            {% endfor %}
        </tr>
        <!--3-->
        <tr id="three">
            <th class="leftNumb">3</th>
            {% for spaces in board.space_list.all %}
            {% if spaces.space_row == 3 %}
            {% if spaces.space_col == "a" %}
            <td id="a3">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "b" %}
            <td id="b3">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "c" %}
            <td id="c3">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "d" %}
            <td id="d3">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "e" %}
            <td id="e3">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "f" %}
            <td id="f3">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "g" %}
            <td id="g3">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "h" %}
            <td id="h3">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% endif %}
            {% endfor %}
        </tr>
        <!--2-->
        <tr id="two">
            <th class="leftNumb">2</th>
            {% for spaces in board.space_list.all %}
            {% if spaces.space_row == 2 %}
            {% if spaces.space_col == "a" %}
            <td id="a2">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "b" %}
            <td id="b2">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "c" %}
            <td id="c2">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "d" %}
            <td id="d2">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "e" %}
            <td id="e2">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "f" %}
            <td id="f2">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "g" %}
            <td id="g2">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "h" %}
            <td id="h2">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% endif %}
            {% endfor %}
        </tr>
        <!--1-->
        <tr id="one">
            <th class="leftNumb">1</th>
            {% for spaces in board.space_list.all %}
            {% if spaces.space_row == 1 %}
            {% if spaces.space_col == "a" %}
            <td id="a1">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "b" %}
            <td id="b1">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "c" %}
            <td id="c1">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "d" %}
            <td id="d1">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "e" %}
            <td id="e1">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "f" %}
            <td id="f1">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "g" %}
            <td id="g1">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% if spaces.space_col == "h" %}
            <td id="h1">{{spaces.space_piece|safe}}</td>
            {% endif %}
            {% endif %}
            {% endfor %}
        </tr>
        <tr id="letterCol">
            <th class="leftNumb">&nbsp</th>
            <th class="leftNumb">a</th>
            <th class="leftNumb">b</th>
            <th class="leftNumb">c</th>
            <th class="leftNumb">d</th>
            <th class="leftNumb">e</th>
            <th class="leftNumb">f</th>
            <th class="leftNumb">g</th>
            <th class="leftNumb">h</th>

        </tr>
    </table>
</div>
<div id="moveContainer">
    <form action="{% url 'chess:home' %}" method="POST">
        {% csrf_token %}
        <div class="form-row">
            <div class="col">
                <input name="fromTextBox" type="text" class="form-control" placeholder="MOVE FROM">
            </div>
            <div class="col">
                <input name="toTextBox" type="text" class="form-control" placeholder="MOVE TO">
            </div>
        </div>
        <br>
        <div id="buttonHolder">
            <button id="moveButton" type="submit" class="btn btn-primary">Move/Save</button>

        </div>
    </form>
    <form action="{% url 'chess:reset' %}" method="POST">
        {% csrf_token %}
        <div id="buttonHolder">
        <button id="resetButton" type="submit" class="btn btn-warning">Reset</button>
    </div>
    </form>
</div>

chessboardApp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="/chess">Home <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link" href="/chess/rules">How to Play</a>
        <a class="nav-item nav-link" href="/chess/history">History</a>
        <a class="nav-item nav-link" href="/chess/about">About</a>
      </div>
    </div>
  </nav>